name: CI - Train Heart Disease Model

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn mlflow matplotlib seaborn

      - name: Run preprocessing
        run: |
          python automate_Yusfitasari.py --input heart.csv --output heart_preprocessing

      - name: Run MLflow Project
        run: |
          mlflow run MLProject/ \
            -P train_path=heart_preprocessing/heart_train.csv \
            -P test_path=heart_preprocessing/heart_test.csv \
            --env-manager=local

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: |
            mlruns/
            confusion_matrix.png
            roc_curve.png
          retention-days: 7
